# Feature Selection


#### Feature selection is a crucial step in machine learning to improve model performance, reduce overfitting, and enhance interpretability.


#### Feature selection involves selecting the most relevant features (variables) from the dataset while discarding irrelevant or redundant ones.

### SelectKBest


SelectKBest is a feature selection method from sklearn.feature_selection that selects the top k features based on a statistical score.
    
It’s widely used to reduce dimensionality and improve model performance by removing irrelevant or redundant features.

Formula: SelectKBest(score_func, k)

    score_func: Function to evaluate each feature (e.g., f_classif, chi2, mutual_info_classif)
    
    k: Number of top features to select

### Filter methods


#### f_classif (ANOVA F-value)


    Type: Supervised, for classification
    
    Method: Measures linear dependency between each feature and the target using ANOVA F-test.
    
    Requirement: Features should be continuous (numeric), target should be categorical.
    
    Pros: Fast, interpretable, standard for many datasets.
    
    Cons: Captures only linear relationships; fails on non-linear dependencies.

from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(score_func=f_classif, k=5)
    
X_new = selector.fit_transform(X, y)

#### chi2 (Chi-squared test)


    Type: Supervised, for classification
    
    Method: Measures dependency between categorical features and target using Chi-squared statistics.
    
    Requirement: Features must be non-negative (0 or positive values).
    
    Pros: Good for categorical/count data like bag-of-words in NLP.
    
    Cons: Only detects linear association, cannot handle negative numbers or continuous features well.

from sklearn.feature_selection import SelectKBest, chi2

selector = SelectKBest(score_func=chi2, k=5)

X_new = selector.fit_transform(X, y)

#### mutual_info_classif (Mutual Information)


    Type: Supervised, for classification
    
    Method: Measures non-linear dependency between each feature and the target.
    
    Requirement: Works for continuous or discrete features.
    
    Pros: Can detect complex non-linear relationships that F-test cannot.
    
    Cons: Slower to compute than f_classif or chi2, less interpretable.

from sklearn.feature_selection import SelectKBest, mutual_info_classif

selector = SelectKBest(score_func=mutual_info_classif, k=5)

X_new = selector.fit_transform(X, y)

| Function                | Feature Type           | Target Type | Captures Linear/Non-linear | Pros                           | Cons                           |
| ----------------------- | ---------------------- | ----------- | -------------------------- | ------------------------------ | ------------------------------ |
| **f_classif**           | Continuous             | Categorical | Linear                     | Fast, simple                   | Misses non-linear dependencies |
| **chi2**                | Non-negative           | Categorical | Linear                     | Works for counts/categorical   | Only positive features, linear |
| **mutual_info_classif** | Continuous or discrete | Categorical | Non-linear                 | Captures complex relationships | Slower, harder to interpret    |


Rule of thumb:
    
    Use f_classif for numeric features, simple and linear.
    
    Use chi2 for count-based or categorical features (like text, one-hot).
    
    Use mutual_info_classif when you suspect non-linear relationships.

#### SelectKBest on load_iris

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

In [2]:
url = "data/iris.csv"

df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])
df

     sepal length  sepal width  petal length  petal width          target
0             4.3          3.0           1.1          0.1     Iris-setosa
1             4.4          2.9           1.4          0.2     Iris-setosa
2             4.4          3.0           1.3          0.2     Iris-setosa
3             4.4          3.2           1.3          0.2     Iris-setosa
4             4.5          2.3           1.3          0.3     Iris-setosa
..            ...          ...           ...          ...             ...
145           7.7          3.8           6.7          2.2  Iris-virginica
146           7.7          2.6           6.9          2.3  Iris-virginica
147           7.7          2.8           6.7          2.0  Iris-virginica
148           7.7          3.0           6.1          2.3  Iris-virginica
149           7.9          3.8           6.4          2.0  Iris-virginica

[150 rows x 5 columns]

In [3]:
features = ['sepal length', 'sepal width', 'petal length', 'petal width']

X = df.loc[:, features].values
X

array([[4.3, 3. , 1.1, 0.1],
       [4.4, 2.9, 1.4, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.1, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3.4, 1.9, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7],
       [5. , 3.6, 1.4, 0.2],
       [5. , 3.4, 1.5, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.5, 1.6, 0.6],
       [5. , 3.3, 1.4, 0.2],
       [5. , 2. , 3.5, 1. ],
       [5. , 2.3, 3.3, 1. ],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 2.5, 3. , 1.1],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.2, 2.7, 3.9, 1.4],
       [5.3, 3.7, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.4, 1.7, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.4, 3. , 4.5, 1.5],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.6, 3. , 4.1, 1.3],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.8, 4.9, 2. ],
       [5.7, 4.4, 1.5, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.7, 2.8, 4.5, 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 4. , 1.2, 0.2],
       [5.8, 2.7, 4.1, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [5.8, 2.6, 4. , 1.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.8, 2.8, 5.1, 2.4],
       [5.8, 2.7, 5.1, 1.9],
       [5.9, 3. , 4.2, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [5.9, 3. , 5.1, 1.8],
       [6. , 2.2, 4. , 1. ],
       [6. , 2.9, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6. , 2.2, 5. , 1.5],
       [6. , 3. , 4.8, 1.8],
       [6.1, 2.9, 4.7, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.8, 4.7, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [6.1, 3. , 4.9, 1.8],
       [6.1, 2.6, 5.6, 1.4],
       [6.2, 2.2, 4.5, 1.5],
       [6.2, 2.9, 4.3, 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6.2, 3.4, 5.4, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.3, 2.5, 4.9, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [6.3, 2.9, 5.6, 1.8],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [6.3, 3.4, 5.6, 2.4],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5],
       [6.4, 2.9, 4.3, 1.3],
       [6.4, 2.7, 5.3, 1.9],
       [6.4, 3.2, 5.3, 2.3],
       [6.4, 2.8, 5.6, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [6.4, 3.1, 5.5, 1.8],
       [6.5, 2.8, 4.6, 1.5],
       [6.5, 3. , 5.8, 2.2],
       [6.5, 3.2, 5.1, 2. ],
       [6.5, 3. , 5.5, 1.8],
       [6.5, 3. , 5.2, 2. ],
       [6.6, 2.9, 4.6, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6.7, 3.1, 4.7, 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.8, 2.8, 4.8, 1.4],
       [6.8, 3. , 5.5, 2.1],
       [6.8, 3.2, 5.9, 2.3],
       [6.9, 3.1, 4.9, 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [6.9, 3.1, 5.4, 2.1],
       [6.9, 3.1, 5.1, 2.3],
       [7. , 3.2, 4.7, 1.4],
       [7.1, 3. , 5.9, 2.1],
       [7.2, 3.6, 6.1, 2.5],
       [7.2, 3.2, 6. , 1.8],
       [7.2, 3. , 5.8, 1.6],
       [7.3, 2.9, 6.3, 1.8],
       [7.4, 2.8, 6.1, 1.9],
       [7.6, 3. , 6.6, 2.1],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [7.7, 3. , 6.1, 2.3],
       [7.9, 3.8, 6.4, 2. ]])

In [4]:
y = df.loc[:,['target']].values

print(y.shape)

(150, 1)

In [5]:
features = ['sepal length', 'sepal width', 'petal length', 'petal width']
features

['sepal length', 'sepal width', 'petal length', 'petal width']

In [6]:
from sklearn.feature_selection import SelectKBest, chi2

selector = SelectKBest(chi2, k=3)

selector.fit(X, y)

for feature, selected in zip(features, selector.get_support()):
    if selected:
        print(feature)

sepal length
petal length
petal width

In [ ]:
selector.scores_,

In [7]:
from sklearn.feature_selection import SelectKBest, chi2

selector = SelectKBest(score_func=chi2, k=2)

selector.fit(X, y.ravel())

for feature, score, selected in zip( features, selector.scores_, selector.get_support()):
    print(feature, score, selected)

sepal length 10.817820878494004 False
sepal width 3.5944990176817346 False
petal length 116.16984746363963 True
petal width 67.24482758620692 True

### nodes


For chi-square X must be non-negative 

No need to do Standard Scalar


selector.get_support() tells us which features were selected


ravel() is used to convert a 2D array into a 1D array.

    But most scikit-learn functions expect the target y to be 1-dimensional:

In [ ]:
import numpy as np

y = np.array([[0],
              [1],
              [2],
              [0]])

print(y.shape)

y = y.ravel()

print(y)
print(y.shape)

### f_classif

In [10]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

url = "data/iris.csv"

df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])

features = ['sepal length', 'sepal width', 'petal length', 'petal width']

x = df.loc[:, features].values

y = df.loc[:,['target']].values

X = StandardScaler().fit_transform(x)

In [11]:
X

array([[-1.87002413e+00, -1.24957601e-01, -1.51186952e+00,
        -1.44444970e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -1.24957601e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.74885626e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.62768839e+00, -1.74477836e+00, -1.39813811e+00,
        -1.18150376e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.50652052e+00,  1.26346019e+00, -1.56873522e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  3.37848329e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.22754100e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
        -1.31297673e+00],
       [-1.26418478e+00, -1.24957601e-01, -1.34127240e+00,
        -1.44444970e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.05694388e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  1.06445364e-01, -1.22754100e+00,
        -1.31297673e+00],
       [-1.26418478e+00, -1.24957601e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-1.14301691e+00, -1.51337539e+00, -2.60824029e-01,
        -2.61192967e-01],
       [-1.14301691e+00, -1.28197243e+00,  4.21564419e-01,
         6.59117823e-01],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00, -1.24957601e-01, -1.22754100e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.22754100e+00,
        -1.05003079e+00],
       [-1.02184904e+00,  3.37848329e-01, -1.45500381e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.03205722e+00, -1.39813811e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  1.03205722e+00, -1.22754100e+00,
        -7.87084847e-01],
       [-1.02184904e+00,  5.69251294e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.02184904e+00, -2.43898725e+00, -1.47092621e-01,
        -2.61192967e-01],
       [-1.02184904e+00, -1.74477836e+00, -2.60824029e-01,
        -2.61192967e-01],
       [-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.18150376e+00],
       [-9.00681170e-01,  1.72626612e+00, -1.28440670e+00,
        -1.18150376e+00],
       [-9.00681170e-01,  1.49486315e+00, -1.28440670e+00,
        -1.05003079e+00],
       [-9.00681170e-01,  5.69251294e-01, -1.17067529e+00,
        -9.18557817e-01],
       [-9.00681170e-01,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-9.00681170e-01,  1.72626612e+00, -1.05694388e+00,
        -1.05003079e+00],
       [-9.00681170e-01,  1.72626612e+00, -1.22754100e+00,
        -1.31297673e+00],
       [-9.00681170e-01, -1.28197243e+00, -4.31421141e-01,
        -1.29719997e-01],
       [-7.79513300e-01,  1.03205722e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-7.79513300e-01,  8.00654259e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-7.79513300e-01,  2.42047502e+00, -1.28440670e+00,
        -1.44444970e+00],
       [-7.79513300e-01, -8.19166497e-01,  8.03701950e-02,
         2.64698913e-01],
       [-6.58345429e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.39813811e+00,
        -1.05003079e+00],
       [-5.37177559e-01,  8.00654259e-01, -1.17067529e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  8.00654259e-01, -1.28440670e+00,
        -1.05003079e+00],
       [-5.37177559e-01, -1.24957601e-01,  4.21564419e-01,
         3.96171883e-01],
       [-4.16009689e-01,  2.65187798e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-4.16009689e-01,  1.03205722e+00, -1.39813811e+00,
        -1.31297673e+00],
       [-4.16009689e-01, -1.74477836e+00,  1.37235899e-01,
         1.33225943e-01],
       [-4.16009689e-01, -1.51337539e+00,  2.35044910e-02,
        -1.29719997e-01],
       [-4.16009689e-01, -1.51337539e+00, -3.33612130e-02,
        -2.61192967e-01],
       [-4.16009689e-01, -1.28197243e+00,  1.37235899e-01,
         1.33225943e-01],
       [-4.16009689e-01, -1.05056946e+00,  3.64698715e-01,
         1.75297293e-03],
       [-2.94841818e-01, -3.56360566e-01, -9.02269170e-02,
         1.33225943e-01],
       [-2.94841818e-01, -1.24957601e-01,  4.21564419e-01,
         3.96171883e-01],
       [-2.94841818e-01, -1.28197243e+00,  8.03701950e-02,
        -1.29719997e-01],
       [-2.94841818e-01, -1.24957601e-01,  1.94101603e-01,
         1.33225943e-01],
       [-2.94841818e-01, -8.19166497e-01,  2.50967307e-01,
         1.33225943e-01],
       [-2.94841818e-01, -5.87763531e-01,  6.49027235e-01,
         1.05353673e+00],
       [-1.73673948e-01,  3.11468391e+00, -1.28440670e+00,
        -1.05003079e+00],
       [-1.73673948e-01,  1.72626612e+00, -1.17067529e+00,
        -1.18150376e+00],
       [-1.73673948e-01, -5.87763531e-01,  4.21564419e-01,
         1.33225943e-01],
       [-1.73673948e-01, -1.05056946e+00, -1.47092621e-01,
        -2.61192967e-01],
       [-1.73673948e-01, -1.24957601e-01,  2.50967307e-01,
         1.75297293e-03],
       [-1.73673948e-01, -3.56360566e-01,  2.50967307e-01,
         1.33225943e-01],
       [-1.73673948e-01, -5.87763531e-01,  1.94101603e-01,
         1.33225943e-01],
       [-1.73673948e-01, -1.28197243e+00,  7.05892939e-01,
         1.05353673e+00],
       [-5.25060772e-02,  2.18907205e+00, -1.45500381e+00,
        -1.31297673e+00],
       [-5.25060772e-02, -8.19166497e-01,  1.94101603e-01,
        -2.61192967e-01],
       [-5.25060772e-02, -8.19166497e-01,  8.03701950e-02,
         1.75297293e-03],
       [-5.25060772e-02, -1.05056946e+00,  1.37235899e-01,
         1.75297293e-03],
       [-5.25060772e-02, -8.19166497e-01,  7.62758643e-01,
         9.22063763e-01],
       [-5.25060772e-02, -5.87763531e-01,  7.62758643e-01,
         1.57942861e+00],
       [-5.25060772e-02, -8.19166497e-01,  7.62758643e-01,
         9.22063763e-01],
       [ 6.86617933e-02, -1.24957601e-01,  2.50967307e-01,
         3.96171883e-01],
       [ 6.86617933e-02,  3.37848329e-01,  5.92161531e-01,
         7.90590793e-01],
       [ 6.86617933e-02, -1.24957601e-01,  7.62758643e-01,
         7.90590793e-01],
       [ 1.89829664e-01, -1.97618132e+00,  1.37235899e-01,
        -2.61192967e-01],
       [ 1.89829664e-01, -3.56360566e-01,  4.21564419e-01,
         3.96171883e-01],
       [ 1.89829664e-01, -8.19166497e-01,  7.62758643e-01,
         5.27644853e-01],
       [ 1.89829664e-01,  8.00654259e-01,  4.21564419e-01,
         5.27644853e-01],
       [ 1.89829664e-01, -1.97618132e+00,  7.05892939e-01,
         3.96171883e-01],
       [ 1.89829664e-01, -1.24957601e-01,  5.92161531e-01,
         7.90590793e-01],
       [ 3.10997534e-01, -3.56360566e-01,  5.35295827e-01,
         2.64698913e-01],
       [ 3.10997534e-01, -5.87763531e-01,  1.37235899e-01,
         1.33225943e-01],
       [ 3.10997534e-01, -5.87763531e-01,  5.35295827e-01,
         1.75297293e-03],
       [ 3.10997534e-01, -1.24957601e-01,  4.78430123e-01,
         2.64698913e-01],
       [ 3.10997534e-01, -1.24957601e-01,  6.49027235e-01,
         7.90590793e-01],
       [ 3.10997534e-01, -1.05056946e+00,  1.04708716e+00,
         2.64698913e-01],
       [ 4.32165405e-01, -1.97618132e+00,  4.21564419e-01,
         3.96171883e-01],
       [ 4.32165405e-01, -3.56360566e-01,  3.07833011e-01,
         1.33225943e-01],
       [ 4.32165405e-01, -5.87763531e-01,  5.92161531e-01,
         7.90590793e-01],
       [ 4.32165405e-01,  8.00654259e-01,  9.33355755e-01,
         1.44795564e+00],
       [ 5.53333275e-01,  5.69251294e-01,  5.35295827e-01,
         5.27644853e-01],
       [ 5.53333275e-01, -1.28197243e+00,  6.49027235e-01,
         3.96171883e-01],
       [ 5.53333275e-01, -1.74477836e+00,  3.64698715e-01,
         1.33225943e-01],
       [ 5.53333275e-01,  5.69251294e-01,  1.27454998e+00,
         1.71090158e+00],
       [ 5.53333275e-01, -3.56360566e-01,  1.04708716e+00,
         7.90590793e-01],
       [ 5.53333275e-01, -8.19166497e-01,  6.49027235e-01,
         7.90590793e-01],
       [ 5.53333275e-01, -5.87763531e-01,  7.62758643e-01,
         3.96171883e-01],
       [ 5.53333275e-01,  8.00654259e-01,  1.04708716e+00,
         1.57942861e+00],
       [ 5.53333275e-01, -1.28197243e+00,  7.05892939e-01,
         9.22063763e-01],
       [ 6.74501145e-01,  3.37848329e-01,  4.21564419e-01,
         3.96171883e-01],
       [ 6.74501145e-01, -3.56360566e-01,  3.07833011e-01,
         1.33225943e-01],
       [ 6.74501145e-01, -8.19166497e-01,  8.76490051e-01,
         9.22063763e-01],
       [ 6.74501145e-01,  3.37848329e-01,  8.76490051e-01,
         1.44795564e+00],
       [ 6.74501145e-01, -5.87763531e-01,  1.04708716e+00,
         1.18500970e+00],
       [ 6.74501145e-01, -5.87763531e-01,  1.04708716e+00,
         1.31648267e+00],
       [ 6.74501145e-01,  1.06445364e-01,  9.90221459e-01,
         7.90590793e-01],
       [ 7.95669016e-01, -5.87763531e-01,  4.78430123e-01,
         3.96171883e-01],
       [ 7.95669016e-01, -1.24957601e-01,  1.16081857e+00,
         1.31648267e+00],
       [ 7.95669016e-01,  3.37848329e-01,  7.62758643e-01,
         1.05353673e+00],
       [ 7.95669016e-01, -1.24957601e-01,  9.90221459e-01,
         7.90590793e-01],
       [ 7.95669016e-01, -1.24957601e-01,  8.19624347e-01,
         1.05353673e+00],
       [ 9.16836886e-01, -3.56360566e-01,  4.78430123e-01,
         1.33225943e-01],
       [ 9.16836886e-01, -1.24957601e-01,  3.64698715e-01,
         2.64698913e-01],
       [ 1.03800476e+00,  1.06445364e-01,  3.64698715e-01,
         2.64698913e-01],
       [ 1.03800476e+00, -1.24957601e-01,  7.05892939e-01,
         6.59117823e-01],
       [ 1.03800476e+00,  1.06445364e-01,  5.35295827e-01,
         3.96171883e-01],
       [ 1.03800476e+00, -1.28197243e+00,  1.16081857e+00,
         7.90590793e-01],
       [ 1.03800476e+00,  5.69251294e-01,  1.10395287e+00,
         1.18500970e+00],
       [ 1.03800476e+00,  1.06445364e-01,  1.04708716e+00,
         1.57942861e+00],
       [ 1.03800476e+00,  5.69251294e-01,  1.10395287e+00,
         1.71090158e+00],
       [ 1.03800476e+00, -1.24957601e-01,  8.19624347e-01,
         1.44795564e+00],
       [ 1.15917263e+00, -5.87763531e-01,  5.92161531e-01,
         2.64698913e-01],
       [ 1.15917263e+00, -1.24957601e-01,  9.90221459e-01,
         1.18500970e+00],
       [ 1.15917263e+00,  3.37848329e-01,  1.21768427e+00,
         1.44795564e+00],
       [ 1.28034050e+00,  1.06445364e-01,  6.49027235e-01,
         3.96171883e-01],
       [ 1.28034050e+00,  3.37848329e-01,  1.10395287e+00,
         1.44795564e+00],
       [ 1.28034050e+00,  1.06445364e-01,  9.33355755e-01,
         1.18500970e+00],
       [ 1.28034050e+00,  1.06445364e-01,  7.62758643e-01,
         1.44795564e+00],
       [ 1.40150837e+00,  3.37848329e-01,  5.35295827e-01,
         2.64698913e-01],
       [ 1.52267624e+00, -1.24957601e-01,  1.21768427e+00,
         1.18500970e+00],
       [ 1.64384411e+00,  1.26346019e+00,  1.33141568e+00,
         1.71090158e+00],
       [ 1.64384411e+00,  3.37848329e-01,  1.27454998e+00,
         7.90590793e-01],
       [ 1.64384411e+00, -1.24957601e-01,  1.16081857e+00,
         5.27644853e-01],
       [ 1.76501198e+00, -3.56360566e-01,  1.44514709e+00,
         7.90590793e-01],
       [ 1.88617985e+00, -5.87763531e-01,  1.33141568e+00,
         9.22063763e-01],
       [ 2.12851559e+00, -1.24957601e-01,  1.61574420e+00,
         1.18500970e+00],
       [ 2.24968346e+00,  1.72626612e+00,  1.67260991e+00,
         1.31648267e+00],
       [ 2.24968346e+00, -1.05056946e+00,  1.78634131e+00,
         1.44795564e+00],
       [ 2.24968346e+00, -5.87763531e-01,  1.67260991e+00,
         1.05353673e+00],
       [ 2.24968346e+00, -1.24957601e-01,  1.33141568e+00,
         1.44795564e+00],
       [ 2.49201920e+00,  1.72626612e+00,  1.50201279e+00,
         1.05353673e+00]])

In [13]:
from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(score_func=f_classif, k=2)

selector.fit(X, y.ravel())

for feature, score, selected in zip(
    features,
    selector.scores_,
    selector.get_support()
):
    print(feature, score, selected)

sepal length 119.26450218450455 False
sepal width 47.364461402993875 False
petal length 1179.034327700235 True
petal width 959.3244057257435 True

### mutual_info_classif

In [15]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif

selector = SelectKBest(
    score_func=mutual_info_classif,
    k=2
)

selector.fit(X, y.ravel())

for feature, score, selected in zip(
    features,
    selector.scores_,
    selector.get_support()
):
    print(feature, score, selected)

sepal length 0.5146129636322101 False
sepal width 0.2549129282153506 False
petal length 0.9935376959706765 True
petal width 0.9961703485855151 True

### SelectPercentile on iris data

SelectPercentile is from sklearn.feature_selection.

    It selects features based on their statistical score.
    
    Instead of k features, you choose a percentile of features, e.g., top 20% features.

    SelectPercentile(score_func=<function>, percentile=<int>)

        score_func: Function to compute feature importance (f_classif, chi2, mutual_info_classif)

        percentile: Integer (0-100) → top X% of features to select

| Method               | Selects          | Use Case                                                                 |
| -------------------- | ---------------- | ------------------------------------------------------------------------ |
| **SelectKBest**      | Top `k` features | When you know exact number of features you want                          |
| **SelectPercentile** | Top `%` features | When you want a relative number of features, independent of dataset size |

In [16]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

url = "data/iris.csv"

df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])

features = ['sepal length', 'sepal width', 'petal length', 'petal width']

X = df.loc[:, features].values

y = df.loc[:,['target']].values

In [17]:

from sklearn.feature_selection import SelectPercentile, chi2

selector = SelectPercentile(chi2, percentile=75)

selector.fit(X, y)

for feature, selected in zip(features, selector.get_support()):
    if selected:
        print(feature)

sepal length
petal length
petal width

# SelectFromModel


SelectFromModel = “Keep only important features based on model weights or importance”

"SelectFromModel is an embedded feature selection technique because it uses model-derived feature importance to select features."

1. Train a model (like SVM, Logistic Regression, Random Forest)

2. The model assigns importance to each feature:
    * Coefficients (coef_) → linear models (Linear/Lasso/Ridge/Logistic Regression)
    * Feature importance (feature_importances_) → tree models (Decision Tree/Random Forest/XGBoost)

3. SelectFromModel:
    * Removes features with low importance
    * Keeps features with high importance

In [28]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

url = "data/iris.csv"

df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])

features = ['sepal length', 'sepal width', 'petal length', 'petal width']

X = df.loc[:, features].values

y = df.loc[:,['target']].values

In [29]:
from sklearn.svm import SVC

from sklearn.feature_selection import SelectFromModel

model = SVC(kernel="linear")

model.fit(X, y)

selector = SelectFromModel(model, prefit=True)

for feature, selected in zip(features, selector.get_support()):
    if selected:
        print(feature)

petal length
petal width

C:\Users\Hp\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [30]:
from sklearn.svm import SVC
from sklearn.feature_selection import SelectFromModel

model = SVC(kernel="linear")

model.fit(X, y.ravel())

selector = SelectFromModel(model, prefit=True)

for feature, selected in zip(features, selector.get_support()):
    if selected:
        print(feature)

petal length
petal width

### Wrapper Methods

SequentialFeatureSelector (SFS) automatically selects the best subset of features by:

    * Training a model multiple times
    
    * Adding or removing features
    
    * Choosing the combination that gives the best performance

* Forward Selection : direction='forward'

    👉 Starts with zero features → adds best ones step by step

* Backward Elimination : direction='backward'

    👉 Starts with all features → removes worst ones step by step

In [18]:
import pandas as pd

df = pd.read_csv("paddy.csv")

y = df["Paddy yield(in Kg)"]

X = df.drop("Paddy yield(in Kg)", axis=1)

X = pd.get_dummies(X, drop_first=True)

In [19]:

from sklearn.linear_model import LinearRegression

from sklearn.feature_selection import SequentialFeatureSelector

model = LinearRegression()

In [20]:

selector = SequentialFeatureSelector( model, n_features_to_select=10, direction="forward", scoring="r2", cv=5)

selector.fit(X, y)

SequentialFeatureSelector(estimator=LinearRegression(), n_features_to_select=10,
                          scoring='r2')

In [21]:
for feature, selected in zip(X.columns, selector.get_support()):
    if selected:
        print(feature)

Hectares
LP_nurseryarea(in Tonnes)
Potassh_50Days
Micronutrients_70Days
Pest_60Day(in ml)
51_70DRain(in mm)
Agriblock_Kurinjipadi
Nursery_wet
Wind Direction_D1_D30_NW
Wind Direction_D31_D60_S

### backward

In [22]:
from sklearn.feature_selection import SequentialFeatureSelector

selector = SequentialFeatureSelector( model, n_features_to_select=10, direction="backward", scoring="r2", cv=5)

selector.fit(X, y)

SequentialFeatureSelector(direction='backward', estimator=LinearRegression(),
                          n_features_to_select=10, scoring='r2')

In [23]:

for feature, selected in zip(X.columns, selector.get_support()):
    if selected:
        print(feature)

Hectares
Potassh_50Days
Min temp_D1_D30
Inst Wind Speed_D61_D90(in Knots)
Agriblock_Kallakurichi
Nursery_wet
Wind Direction_D1_D30_W
Wind Direction_D31_D60_WNW
Wind Direction_D91_D120_NW
Wind Direction_D91_D120_S

| Forward Selection        | Backward Selection             |
| ------------------------ | ------------------------------ |
| Starts with 0 features   | Starts with all features       |
| Adds best feature        | Removes worst feature          |
| Faster for many features | Better when dataset small      |
| Good for large datasets  | More computationally expensive |

### RFE

In [24]:
import pandas as pd

df = pd.read_csv("paddy.csv")

y = df["Paddy yield(in Kg)"]
X = df.drop("Paddy yield(in Kg)", axis=1)

X = pd.get_dummies(X, drop_first=True)

In [25]:

from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

model = LinearRegression()

In [26]:

rfe = RFE( model, n_features_to_select=10)

rfe.fit(X, y)

RFE(estimator=LinearRegression(), n_features_to_select=10)

In [27]:
for feature, selected in zip(X.columns, rfe.get_support()):
    if selected:
        print(feature)

Pest_60Day(in ml)
Max temp_D31_D60
Max temp_D61_D90
Inst Wind Speed_D1_D30(in Knots)
Inst Wind Speed_D91_D120(in Knots)
Trash(in bundles)
Variety_delux ponni
Variety_ponmani
Soil Types_clay
Nursery_wet

#### Embedded methods

Embedded methods perform feature selection automatically during the training of a Machine Learning model. 

Unlike filter methods (before training) and wrapper methods (after repeatedly training models), embedded methods combine model building and feature selection into a single process.

Dataset
   │
   ▼
Train Machine Learning Model
   │
   ▼
Model Automatically Evaluates Features
   │
   ▼
Important Features are Selected
Less Important Features are Ignored/Removed

| Method                                              | ML Model                   | How Features are Selected                                 |
| --------------------------------------------------- | -------------------------- | --------------------------------------------------------- |
| **Lasso Regression (L1)**                           | Linear Regression          | Sets some coefficients to **0**, removing those features. |
| **Decision Tree**                                   | Decision Tree              | Selects features that provide the best splits.            |
| **Random Forest**                                   | Ensemble of Decision Trees | Ranks features using **feature importance** scores.       |
| **Gradient Boosting (XGBoost, LightGBM, CatBoost)** | Boosting Models            | Calculates feature importance during training.            |

### Logistic Regression (Embedded Method)

In [35]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

data = pd.read_csv("data/diabetes.csv")
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [39]:

X = data.drop("Outcome", axis=1)
y = data["Outcome"]

model = LogisticRegression(max_iter=1000)

model.fit(X, y)
print(model.coef_)

[[ 1.22493039e-01  3.51094511e-02 -1.32990899e-02  7.78941937e-04
  -1.17362216e-03  8.96467361e-02  8.67835105e-01  1.49859646e-02]]

In [44]:
from sklearn.feature_selection import SelectFromModel

selector = SelectFromModel( model, threshold=0.01)

X_selected = selector.fit_transform(X, y)

In [45]:
selected_features = X.columns[selector.get_support()]

print("Selected Features:")
print(selected_features.tolist())

Selected Features:
['Pregnancies', 'Glucose', 'BloodPressure', 'BMI', 'DiabetesPedigreeFunction', 'Age']

In [34]:
for feature, coefficient in zip(X.columns, model.coef_[0]):
    print(feature, coefficient)

Pregnancies 0.12249303923213437
Glucose 0.03510945111031793
BloodPressure -0.013299089860342835
SkinThickness 0.0007789419366195091
Insulin -0.001173622156146077
BMI 0.08964673614986862
DiabetesPedigreeFunction 0.8678351046353368
Age 0.014985964609639711

Feature                    Coefficient
---------------------------------------
Pregnancies                  0.40   ✓
Glucose                      0.02   ✗
BloodPressure               -0.05   ✗
SkinThickness                0.01   ✗
Insulin                     -0.03   ✗
BMI                          0.35   ✓
DiabetesPedigreeFunction     0.45   ✓
Age                          0.04   ✗


model.fit() → train the model

SelectFromModel() → use the model to select features

get_support() → tell us which features were selected

### What is SelectFromModel?

SelectFromModel is a feature selection utility in scikit-learn that uses the importance or coefficients of an ML model to select the most important features.

It is called an embedded method because the feature importance comes from a trained model.

### Why is it an Embedded Method?

Because:
    
    The model is trained first.
    
    The model learns coefficients (Lasso) or feature importances (Random Forest).
    
    SelectFromModel uses those learned values to keep important features and discard the rest.

So the feature selection depends on the trained model, which makes it an embedded method.

### working with linear models and tree models for feature selection

##### linear models


A linear model is a model that makes predictions using a weighted combination of input features.

1. coef_

    model.coef_

    This gives the coefficient/weight of each feature.

    model.coef_[0]

2. threshold

    Used with feature-selection tools such as SelectFromModel:

    SelectFromModel(model, threshold=0.1)

    Meaning:

    Keep features whose importance is ≥ 0.1.

3. C — L1 Logistic Regression

    LogisticRegression(
        C=0.1,
        l1_ratio=1.0
    )

    C controls regularization strength.

4. l1_ratio

    For Logistic Regression's regularization:
    
    l1_ratio=1.0


#### Tree Models — Feature Selection Parameters


1. feature_importances_

    For tree models:

    model.feature_importances_

    This gives the importance of each feature.

| Model              | Feature-selection parameter |
| ------------------ | --------------------------- |
| **Linear models**  | `coef_`                     |
|                    | `abs(coef_)`                |
|                    | `C`                         |
|                    | `l1_ratio`                  |
| **Tree models**    | `feature_importances_`      |
|                    | `n_estimators`              |
|                    | `max_depth`                 |
| **Selection tool** | `threshold`                 |

In [46]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

data = pd.read_csv("data/diabetes.csv")

X = data.drop("Outcome", axis=1)
y = data["Outcome"]

model = LogisticRegression(max_iter=1000)

model.fit(X, y)

for feature, coef in zip(X.columns, model.coef_[0]):
    print(feature, coef)

Pregnancies 0.12249303923213437
Glucose 0.03510945111031793
BloodPressure -0.013299089860342835
SkinThickness 0.0007789419366195091
Insulin -0.001173622156146077
BMI 0.08964673614986862
DiabetesPedigreeFunction 0.8678351046353368
Age 0.014985964609639711

In [48]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

data = pd.read_csv("data/diabetes.csv")

X = data.drop("Outcome", axis=1)
y = data["Outcome"]

model = LogisticRegression(max_iter=1000)
model.fit(X, y)

# Feature importance
importance = abs(model.coef_[0])

result = pd.DataFrame({
    "Feature": X.columns,
    "Importance": importance
})

# Top 3
top3 = result.sort_values(
    "Importance",
    ascending=False
).head(5)

print(top3)

                    Feature  Importance
6  DiabetesPedigreeFunction    0.867835
0               Pregnancies    0.122493
5                       BMI    0.089647
1                   Glucose    0.035109
7                       Age    0.014986

In [50]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

data = pd.read_csv("data/diabetes.csv")

X = data.drop("Outcome", axis=1)
y = data["Outcome"]

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X, y)

for feature, importance in zip(
    X.columns,
    model.feature_importances_
):
    print(feature, importance)

Pregnancies 0.08501656218522641
Glucose 0.2671417574733811
BloodPressure 0.0886596828565411
SkinThickness 0.06460412700022039
Insulin 0.07154711634335888
BMI 0.16876864301424507
DiabetesPedigreeFunction 0.12269526460401114
Age 0.13156684652301587

In [51]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

data = pd.read_csv("data/diabetes.csv")

X = data.drop("Outcome", axis=1)
y = data["Outcome"]

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X, y)

RandomForestClassifier(random_state=42)

In [ ]:

result = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

In [53]:

top3 = result.sort_values( "Importance", ascending=False ).head(5)

print("Top 3 Features:")
print(top3)

Top 3 Features:
                    Feature  Importance
6  DiabetesPedigreeFunction    0.867835
0               Pregnancies    0.122493
5                       BMI    0.089647
1                   Glucose    0.035109
7                       Age    0.014986